#set base directory variable
datadir <- "/home/gloria/Documentos/2.Master_Bioinfomatica_i_Bioestadistica/TFM/RNA_seq/counts"

#list the files from the directory variable and convert to data frame that will be the phenodata
phdata_fulla_treat<-data.frame(fname=list.files(path=datadir,pattern="*"),stringsAsFactors=FALSE)


library(tidyverse)
#modify phenodata dataset to stablish for each sample the levels of the variables
phdata_fulla_treat <- phdata_fulla_treat %>% transmute(sample=substr(fname, 1,8),fname)
phdata_fulla_treat <- phdata_fulla_treat %>%
  mutate(map=as.factor(substr(fname,1,1)),
         trt=substr(fname,6,6),
         pop=substr(fname,3,4),
         md5=tools::md5sum(file.path(datadir,fname)))


library(DESeq2)
#to import count files generated by HTSeq.
dds_fulla_treat<-DESeqDataSetFromHTSeqCount(sampleTable=phdata_fulla_treat, 
                                            directory=datadir, design= ~pop)

#create and plot a PCA
vsd_fulla_treat <- vst(dds_fulla_treat)
pcaData_treat <- plotPCA(vsd_fulla_treat,
                         intgroup = c("trt","map", "pop"),
                         returnData = TRUE)
percentVar <- round(100 * attr(pcaData_treat, "percentVar"))
plot_title_ <- expression("1.PCA all north")
palette_new_d = c("#00a087", "#3498db",  "#f1c40f", "#4c5488")
ggplot(pcaData_treat, aes(x = PC1, y = PC2, color = trt, shape = pop)) +
  geom_point(size = 2) +
  xlab(paste0("PC1: ", percentVar[1], "% of variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% of variance")) +
  ggtitle(plot_title_) +
  scale_color_manual(values = palette_new_d, labels = c("Control","Treatment"),
                     name = "Treatment") +
  scale_shape_discrete(labels=c("Resistant","Sensitive"), name="Tolerance") +
  theme(axis.text.x = element_text(size=rel(2))) + 
  theme(axis.title.x = element_text(size=rel(2))) + 
  theme(axis.title.y = element_text(size=rel(2))) + 
  theme(legend.key.size = unit(1, units = "cm")) + 
  theme(legend.text=element_text(size=15)) + 
  theme(legend.title = element_text(size=20, hjust=0.5)) +
  theme(plot.title=element_text(hjust=0.5, size = 20)) +
  guides(colour = guide_legend(override.aes = list(size=10), 
                               title = "")) +
  stat_ellipse(aes(x=PC1, y=PC2, group=trt, colour = trt), geom = "polygon", alpha =0.1)


#Defferential expressiona anlysis
ddsDE_fulla_treat <- DESeq(dds_fulla_treat)

# To obtain the normalized counts
norm_counts_treat <- data.frame(counts(ddsDE_fulla_treat, normalized = TRUE))

#Exrtraction of log2foldChange and padj values
norm_counts_treat_results <- results((ddsDE_fulla_treat[rowMeans(counts(ddsDE_fulla_treat))>1,]))

#Extract the most siginficative ones (padj <= 0.05 and log3FoldChange >2)
norm_counts_treat_results <- na.omit(norm_counts_treat_results)
sigGenes_treat_norm <-rownames(norm_counts_treat_results[norm_counts_treat_results$padj <= .05 & abs(norm_counts_treat_results$log2FoldChange) > 2, ],)

#Save them
write.csv(norm_counts_treat, "/home/gloria/Documentos/2.Master_Bioinfomatica_i_Bioestadistica/TFM/RNA_seq/log2_2/analisi_definitiu_m/fulla/all_north/all_north.csv")
write.csv(sigGenes_treat_norm, "/home/gloria/Documentos/2.Master_Bioinfomatica_i_Bioestadistica/TFM/RNA_seq/log2_2/analisi_definitiu_m/fulla/all_north/SigGenes_all_north_.csv")

library(dplyr)

#add the counts to the sigGenes
sigGenes_treat_norm_expresio <- merge(sigGenes_treat_norm, norm_counts_treat, by = "gene")

#DEGs with their counts
write.csv(sigGenes_treat_norm_expresio, "/home/gloria/Documentos/2.Master_Bioinfomatica_i_Bioestadistica/TFM/RNA_seq/log2_2/analisi_definitiu_m/fulla/all_north/sigGenes_all_info.csv")
